'use client';
import Link from 'next/link';
import { useState } from 'react';
import { GATES, EXITS, LIMITS, PRODUCT } from '@/lib/product';
import { Terminal } from '../Terminal';
import { Disclosure } from './SiteView';
export default function SimpleGate({id,choose}: {id:string;choose:(id:string)=>void}) {
 const [copy,setCopy] = useState('Copy demo command');
 const gate = GATES.find(g => g.id === id) || GATES[0];
 return <main className="sv-home"><section className="sv-hero"><div><small>CHECK THE WORK BEFORE IT SHIPS</small><h1>Make the approved plan matter.</h1><p>Write rules for finished work. Deferless checks them and stops the handoff when something is missing or wrong.</p></div><div className="sv-action"><h2>Try the package locally</h2><p>No account or web upload. Run the published demo in your own terminal.</p><pre>{PRODUCT.install}</pre><button className="sv-copy" onClick={async () => {try {await navigator.clipboard.writeText(PRODUCT.install);setCopy('Copied');}catch {setCopy('Select the command above to copy');}}}>{copy}</button><a href={PRODUCT.npm}>Get deferless on npm ↗</a><p>MIT licensed. {PRODUCT.node}. This website explains the package; it does not run checks on your files.</p></div></section>
 <section className="sv-section"><h2>Choose what you need to check</h2><p>The same four gates as Console. Your selection stays when you switch views.</p><div className="sv-gates">{GATES.map(g => <button key={g.id} aria-pressed={id === g.id} onClick={() => choose(g.id)}>{g.title}</button>)}</div><article className="sv-result"><h3>{gate.title}</h3><p>{gate.what}</p><h4>Run this in your project</h4><pre>{gate.usage}</pre><Disclosure title={`What this gate checks · ${gate.clauses.length}`}><dl>{gate.clauses.map(c => <div className="sv-row" key={c.name}><dt>{c.name}</dt><dd><p>{c.reads}</p><p>{c.refuses}</p></dd></div>)}</dl></Disclosure><Disclosure title="How to understand the answer"><dl>{EXITS.filter(e => (gate.exits as readonly string[]).includes(e.code)).map(e => <div className="sv-row" key={e.code}><dt>Exit {e.code}: {e.name}</dt><dd>{e.say}</dd></div>)}</dl><p>Could not check is never a pass. Resolve the cause and run the check again.</p></Disclosure></article></section>
 <section className="sv-section"><h2>See a real captured example</h2><p>Two documentation folders: one matches the approved plan, one does not. This is captured package output, not a check of your project.</p><Disclosure title="Open the demo output"><Terminal/></Disclosure></section>
 <section className="sv-section"><h2>Know the limits before relying on it</h2><p>You write the spec by hand. A passing check does not prove that the agent built the right thing.</p><Disclosure title="Requirements and limitations"><dl>{LIMITS.map(l => <div className="sv-row" key={l.id}><dt>{l.head}</dt><dd>{l.say}</dd></div>)}</dl></Disclosure><div className="sv-links"><Link href="/kinds">Browse every check</Link><Link href="/method">Read the method and sources</Link><a href="mailto:hello@thecompound.tech">Ask for help</a></div></section></main>;
}
