#!/usr/bin/env node
/* FREEZE THE REAL `deferless demo` OUTPUT INTO THIS TREE.
 *
 *   npm run capture
 *
 * ⛔ THE TERMINAL BLOCK ON THIS SITE IS NOT TYPED, IT IS CAPTURED. A page that retypes a
 * program's output drifts from it the first time the program changes a word, and nothing
 * errors when it does: the block still looks like output. This runs the installed package
 * and writes exactly what came back, so the only way the page can be wrong is for the
 * capture to be stale, which scripts/check-register.mjs refuses.
 *
 * ⛔ IT EMITS A MODULE, NOT A DATA FILE. The Worker this site ships to has no filesystem, so
 * a page that reads data/ at request time answers 500 in production and 200 in dev. Measured
 * on shelfcite, 2026-09-19: "stop reading data/ and public/logos off a filesystem the Worker
 * doesn't have". The capture is compiled in.
 *
 * ⛔ ANSI IS STRIPPED AND NOTHING ELSE IS. Colour is the terminal's, not the program's. Every
 * other byte, the box marks and the dashes included, is the package's own output and is
 * reproduced as it came.
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { homedir } from 'node:os';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/* The package, in the order a reader would reach for it: an install in this tree first, then
 * the working copy on this machine. A capture that silently fell back to something else would
 * be a capture of the wrong program. */
const CANDIDATES = [
  join(ROOT, 'node_modules/deferless/bin/deferless.mjs'),
  join(homedir(), 'CompoundLabs/deferless/bin/deferless.mjs'),
];
const BIN = CANDIDATES.find((p) => existsSync(p));
if (!BIN) {
  console.error('capture: no deferless on this machine. Looked at:');
  for (const c of CANDIDATES) console.error('  ' + c);
  process.exit(2);
}

const version = JSON.parse(
  execFileSync('node', ['-p', 'JSON.stringify(require(process.argv[1]))', resolve(BIN, '../../package.json')], {
    encoding: 'utf8',
  }),
).version;

/* ⛔ STDERR IS MERGED, AND THE FIRST CUT OF THIS SCRIPT DID NOT DO IT. `deferless demo` writes
 * its narration to stdout and the whole failing half to stderr, so taking stdout alone captured
 * 29 of the 44 lines and lost every violation the demo exists to show. It printed
 * "0 marked lines" and looked like a successful capture. Merged through a shell so the two
 * streams interleave in the order a terminal would show them.
 *
 * ⛔ AND IT RUNS FROM THE PACKAGE ROOT. The gate prints its spec path relative to the cwd, so
 * running it from anywhere else bakes this machine's directory layout into the page. */
const PKG = resolve(BIN, '../..');
const raw = execFileSync('sh', ['-c', `node ${JSON.stringify(BIN)} demo 2>&1`], {
  encoding: 'utf8',
  cwd: PKG,
  maxBuffer: 4 * 1024 * 1024,
});

/* CSI sequences only. Nothing else about the bytes is touched. */
const ESC = String.fromCharCode(27);
const ansi = new RegExp(ESC + '\\[[0-9;]*[A-Za-z]', 'g');
const clean = raw.replace(ansi, '').replace(/\r\n/g, '\n').trimEnd();

/* The absolute path of whoever ran the capture is not a fact about the package. The two lines
 * that print an output directory are rewritten to the relative form the rest of the block
 * already uses, so the capture reads the same on any machine. */
const body = clean.split(PKG + '/').join('').split(homedir()).join('~');

const lines = body.split('\n');
/* The findings only. The tally line above them starts with the same mark and is not a finding,
 * so it is excluded by the indent the gate prints it at rather than by counting and then
 * subtracting one. */
const violations = lines.filter((l) => l.startsWith('  ✖ ')).length;
const tally = lines.some((l) => l.startsWith('✖ ') && l.includes('violation(s)'));
const passed = lines.some((l) => l.startsWith('✔ ') && l.includes('check(s) passed'));

/* ⛔ A CAPTURE THAT LOST THE FAILING HALF IS NOT A CAPTURE. The demo's whole subject is the
 * five violations, and stdout alone carries neither them nor the tally. A run that comes back
 * without them is a broken capture, not an empty one. Exit 2, never a file. */
if (!passed || !tally || violations !== 5) {
  console.error(
    `capture: expected the passing line, the tally and 5 findings. Got passed=${passed} tally=${tally} findings=${violations}. Nothing written.`,
  );
  process.exit(2);
}

mkdirSync(resolve(ROOT, 'src/lib'), { recursive: true });
writeFileSync(
  resolve(ROOT, 'src/lib/demo.ts'),
  [
    '/* GENERATED by scripts/capture.mjs. Do not edit.',
    ' *',
    ' * The output of `deferless demo`, captured from the package itself. Colour removed, every',
    ' * other byte as the program wrote it. Re-run `npm run capture` to refresh.',
    ' */',
    `export const DEMO_VERSION = ${JSON.stringify(version)};`,
    `export const DEMO_CAPTURED_AT = ${JSON.stringify(new Date().toISOString().slice(0, 10))};`,
    `export const DEMO_OUTPUT = ${JSON.stringify(body)};`,
    '',
  ].join('\n'),
);

process.stdout.write(
  `captured deferless@${version} demo: ${lines.length} lines, ${violations} marked lines, ${body.length} bytes\n`,
);
