#!/usr/bin/env node
/* Vendors the Phosphor Regular glyphs this app draws, from the Phosphor core repo.
 *
 *   npm run icons
 *
 * ⛔ FROM THE SOURCE, NEVER FROM ANOTHER PRODUCT'S TREE. A copy of a copy has no source to
 * re-read, and the estate has no shared component library to take one from: those repos were
 * purged on 2026-09-14 and every app vendors its own.
 *
 * The glyphs are compiled into src/lib/phosphor.ts as path bodies in currentColor, so a glyph
 * takes the ink of whatever sits beside it. No icon font and no runtime CDN.
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'vendor/phosphor');
const BASE = 'https://raw.githubusercontent.com/phosphor-icons/core/main/assets/regular';
const LICENSE = 'https://raw.githubusercontent.com/phosphor-icons/core/main/LICENSE';

/* One glyph per destination and one per gate. Nothing here is decorative, so a glyph with no
 * caller is a glyph to delete rather than to keep in case. */
const WANT = [
  'terminal-window', // the captured output
  'file-text', // the plan gate
  'seal-check', // the promote gate
  'globe-hemisphere-west', // the render gate
  'stack-simple', // the deploy gate
  'prohibit', // the three things that do not exist
  'list-numbers', // the exit codes
  'warning-circle', // the honest limitations
  'lightning', // the run line
  'arrow-square-out', // an outward link
];

await mkdir(OUT, { recursive: true });
const index = {};
for (const name of WANT) {
  const url = `${BASE}/${name}.svg`;
  const r = await fetch(url);
  if (!r.ok) throw new Error(`HTTP ${r.status} on ${url}`);
  const svg = await r.text();
  const body = svg
    .replace(/<\?xml[\s\S]*?\?>/g, '')
    .replace(/<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/fill="#[0-9a-fA-F]{3,8}"/g, 'fill="currentColor"')
    .trim();
  await writeFile(resolve(OUT, `${name}.svg`), svg);
  index[name] = body;
  process.stdout.write(`${name}  ${svg.length}b\n`);
}
const lic = await fetch(LICENSE);
if (!lic.ok) throw new Error(`HTTP ${lic.status} on the licence`);
await writeFile(resolve(OUT, 'LICENSE'), await lic.text());

await writeFile(
  resolve(ROOT, 'src/lib/phosphor.ts'),
  `// GENERATED by scripts/icons.mjs from ${BASE}\n` +
    `// Phosphor Icons, MIT. The licence is vendored at vendor/phosphor/LICENSE.\n` +
    `export const GLYPH: Record<string, string> = ${JSON.stringify(index, null, 1)};\n` +
    `export type GlyphName = keyof typeof GLYPH;\n`,
);
process.stdout.write(`\nwrote src/lib/phosphor.ts, ${WANT.length} glyphs\n`);
